---
features:
  - |
    Adds support for creating, reading, and deleting application credentials.
    With application credentials, a user can grant their applications limited
    access to their cloud resources. Applications can use keystoneauth with
    the `v3applicationcredential` auth plugin to authenticate with keystone
    without needing the user's password.
