- job:
    name: keystoneclient-devstack-functional
    parent: devstack-minimal
    timeout: 4200
    required-projects:
      - openstack/keystone
      - openstack/python-keystoneclient
    run: playbooks/run-ds-tox.yaml
    post-run: playbooks/tox-post.yaml
    vars:
      devstack_localrc:
        USE_PYTHON3: true
      devstack_services:
        key: true
      tox_envlist: functional
      zuul_work_dir: src/opendev.org/openstack/python-keystoneclient

- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - release-notes-jobs-python3
    check:
      jobs:
        - keystoneclient-devstack-functional
    gate:
      jobs:
        - keystoneclient-devstack-functional
